### ISSUE TITLE
Short-term SvelteKit rewrite to-do list

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Resource-Pack/Website#85]
- [ ] modding (requires API changes)
	- [ ] Faithful 32x
	- [ ] Classic Faithful 32x
	- [ ] installation instructions
- [x] FAQ page
	- [x] making the page itself
	- [x] migrating strings.json to the complibot repository and use fetch to retrieve 
and use it
		- Should we be doing this though? The Discord FAQ entries are not relevant for the website
- [ ] (finish) history page
	- [ ] finish (updating) the timeline document (let's do this when everything else is done so we don't have to constantly update it as time goes on)
	- [ ] implement the strings and formatting
- [x] ~~branding page (docs)~~ very small priority, not needed to finish rewrite
- [x] new downloads page
- [ ] installation instruction pages
	- [ ] add some animations
	- [ ] implement the individual guide pages
- [x] adding "/latest" for posts
- [x] fix posts not working when being something other than faithful 32x or 64x
- [x] fix gallery showing "first" instead of java on initial load
- [ ] #111
- [ ] pack selection guide (design + implement)
- [x] redo pack about pages (make banner consistent with main page in size, use wordmark instead of logotext, move about text below banner)
- [x] redo main page cards
- [ ] figure out a better way to link the pack selection guide on the main page
- [ ] addon installation guide
- [x] implement breadcrumbs (something that shows the path to your page as you navigate)
- [ ] translations
	- [ ] changing language and navigating to other pages does not apply previously selected language
	- [ ] make the translation selector a dropdown menu
	- [ ] set the default language from the browsers language (using `window.navigator.language`)
	- [ ] store language in localstorage and not the url
	- [ ] generate available languages from json files in lang folder (right now every available language needs to be specified manually)
	- [x] localized dates
- [ ] placeholders
	- [ ] teams page (images, descriptions, data)
	- [x] about page (images)
	- [ ] main pack page comparisons and screenshots
	- [x] downloads page (classic faithful is missing + the rework as mentioned above)
	- [ ] installation instruction images
		- [ ] Android
		- [ ] Screenshots of the Java & Bedrock main menu screen

**Comment by Pomi108** [comment]
- [ ] move the language button to the header since it should be accessible all the time

**Comment by 3vorp** [comment]
> * [ ]  move the language button to the header since it should be accessible all the time

most sites I see have language at the bottom, plus it's symmetrical with the theme button so I'm not a huge fan of this

examples:
https://discord.com/
https://www.minecraft.net/

**Comment by 3vorp** [comment]
oh also — where would we even put it, it would make everything off center on the header/navbar lol

**Comment by 3vorp** [comment]
small thing that would be nice — if navigator.language detects that the browser is using `en-US`

you can test this by running 
```js
console.log(navigator.language))
```

we should use m/d/y

I know it's a small thing but d/m/y and m/d/y are ambiguous formats, the US alone makes up a decent chunk of our traffic, and y/m/d doesn't read very naturally (according to pomi at least, I have no issues with it personally)

**Comment by 3vorp** [comment]
also another random suggestion just in general

can we have posts not have escape characters within the urls if possible

https://faithfulpack.net/License%20Update just looks really ugly, add-ons already fix this such as with https://faithfulpack.net/addons/2d-bed-icons and this is even implemented on the beta site, but only for addons

I know the post url structure is getting actively rewritten atm because of the weird `500 internal error`s so this would be nice to implement in the process

**Comment by RobertRR11** [comment]
just edit the links, they are not hardcoded

**Comment by 3vorp** [comment]
true but we'd need redirects

**Comment by RobertRR11** [comment]
definitely not gonna do that

**Comment by 3vorp** [comment]
another one

you can't open more than one footer category at a time when using the mobile layout, while this seems to be intended behavior I'd definitely rather have it so that you can open as many as you want

if people don't like the clutter or whatever we can just have a "close all" button near the top or something if necessary

**Comment by 3vorp** [comment]
here's a bunch of extra stuff I'm putting in one post because this is getting rather long

this is also generally more long-term stuff that I've seen mentioned but never really centralized

- gallery stuff:
   - fix gallery showing "first" instead of java
   - generally finish up the gallery, also implement classic faithful
   - add authors page and that whole system
- user management
   - implement addon submission system and that whole thing
   - add post authors and the ability for certain roles to create them (also posts can optionally hide all authors for general announcements)
   - add user profile page (see ![concept art](https://media.discordapp.net/attachments/881657726768390154/1100317081104306207/image.png) for more info)
      - whatever design we end up using for the cards would end up going on the left bar
      - generate background color based on the user's discord banner color, or just let the user pick it themselves
      - a vague card concept that more than two people have agreed on is <img src="https://media.discordapp.net/attachments/881657726768390154/1101284781414694985/image.png" alt="card concept" height="500"/>
   - revamp the role system to be constantly updated and possibly synced with discord since afaik the api stores that stuff
   - add a manager-exclusive dashboard with the functionality of the current manager section in the webapp (changing paths/contributors/uses/approving addons)
      - _possibly_ give council the ability to approve addons (I'm fairly certain we agreed on this at some point)
      - while we're at it we should also be able to add contributors without discord accounts, currently CF basically cannot have proper contributions listed as a result of this problem
   - general user dashboard for submitting addons directly integrated into the site (see github and modrinth for references)
      - add a profile button somewhere on the header which links your discord account to the site
      - there would be a settings menu where the profile button is where you can customize your card (or make it only visible on addons or something for privacy)
      - section to update and create addons directly integrated on the site, similar to the current webapp

**Comment by RobertRR11** [comment]
I'd make this a seperate issue because most things you listed will not get implemented in the initial release

**Comment by 3vorp** [comment]
done, renamed this one to a short term TDL to make more sense

also til you can edit other people's issue posts this is useful

**Comment by 3vorp** [comment]
- [ ] add a visible date to posts because it's really easy to get lost otherwise (this is tracked already in the header so just make it visible on the page itself)

**Comment by 3vorp** [comment]
btw with recent api changes by me and rolf the modding api changes should be much easier to facilitate now since only the api now has to be changed to accommodate new collections rather than figuring out everywhere that's configured to use firestorm

**Comment by Pomi108** [comment]
We need to figure out a way to exclude Discord-specific FAQ entries from the list, since they're not relevant for the readers of the site

**Comment by 3vorp** [comment]
could just add a field in the faq json to hide it on the site like 

"discord_exclusive": boolean

**Comment by 3vorp** [comment]
Given the state of the website now, I don't think most of the remaining items are relevant anymore—there's a handful of specific ideas here I might want to revisit at some point in the future, but I'd rather treat those as individual features rather than some sort of broader overhaul. This issue has definitely served its purpose at this point lol

**Comment by RobertRR11** [comment]
hehe

**Comment by 3vorp** [comment]
haha

**Comment by TheRolfFR** [comment]
hoho

**Comment by Pomi108** [comment]
huhu
