### ISSUE TITLE
Long-term SvelteKit rewrite to-do list

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/Website#86]
- [ ] gallery stuff:
   - [ ] implement classic faithful
   - [ ] add authors page and that whole system
- [ ] user management
   - [ ] implement add-on submission system and that whole thing
   - [ ] add post authors and the ability for certain roles to create them (also posts can optionally hide all authors for general announcements)
   - [x] add user profile page (see ![concept art](https://github.com/user-attachments/assets/b85f2a49-ea97-452d-b325-6bebf5ed3497) for more info)
      - [ ] whatever design we end up using for the cards would end up going on the left bar
      - [ ] generate background color based on the user's discord banner color, or just let the user pick it themselves
      - [ ] a vague card concept that more than two people have agreed on is <img src="https://github.com/user-attachments/assets/d0bb710a-5dfa-4925-ac1b-c061803d9072" alt="card concept" height="500"/>
   - [ ] revamp the role system to be constantly updated and possibly synced with discord since afaik the discord api stores that stuff and you can track it via complibot or something
   - [ ] add a manager-exclusive dashboard with the functionality of the current manager section in the webapp (changing paths/contributors/uses/approving add-ons)
      - [x] _possibly_ give council the ability to approve add-ons (I'm fairly certain we agreed on this at some point)
      - [x] while we're at it we should also be able to add contributors without discord accounts, currently CF basically cannot have proper contributions listed as a result of this problem
      - [x] be able to edit posts via a similar UI to the add-on descriptions where you can insert changelogs, etc without manually editing markdown and header content — this should be implemented along with the post author system to make sense
   - [ ] general user dashboard for submitting add-ons directly integrated into the site (see github and modrinth for references)
      - [ ] add a profile button somewhere on the header which links your discord account to the site
      - [ ] there would be a settings menu where the profile button is where you can customize your card (or make it only visible on addons or something for privacy)
      - [ ] section to update and create add-ons directly integrated on the site, similar to the current webapp
- [ ] larger qol changes
   - [x] search bar in the pack menu (this would require indexing all articles, mods, and add-on posts, and showing them in some sort of dialog, might be a bit of a pain to optimize it)
- [ ] stats page rework
   - [ ] have a way to fetch stats from curseforge, modrinth, github, and the database, and keep a json of approximated mcpedl and modrinth values
   - [ ] add all of them together for a "total download count" section
   - [ ] rework the entire page into a spreadsheet-like format showing the total downloads for each pack, where those downloads are distributed, mods, addons, the works
   - [ ] add a proper description and link it more heavily to show that we do in fact have the numbers to back ourselves up
   - [ ] concept art at ![Image](https://github.com/user-attachments/assets/05986ab1-6879-46a7-b010-f5e424b8cd87), loosely based off an old version of discord's site showing the features discord offers over other similar products
   - [ ] have "most downloaded" and "most recent" categories, etc, so it doesn't look horribly bland

**Comment by 3vorp** [comment]
Given the state of the website now, I don't think most of the remaining items are relevant anymore—there's a handful of specific ideas here I might want to revisit at some point in the future, but I'd rather treat those as individual features rather than some sort of broader overhaul. This issue has definitely served its purpose at this point lol
